repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff autofix
        entry: uv run ruff check --fix
        language: system
        types_or: [python, pyi, jupyter]

      - id: black
        name: Black format
        entry: uv run black
        language: system
        types_or: [python, pyi, jupyter]

      - id: project-check
        name: Project checks
        entry: make check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

